### ISSUE TITLE
Iteration 3 -- see associate user stories in the milestone for iteration 3

### ISSUE THREAD

**Issue by shayan-golafshani** [shayan-golafshani/rancid-tomatillos#23]
---------------------------------------------

- [x] Set up fetch calls

- [x] add error handling for server errors
- [x] clean up code and make sure it's dry
- [x] update project board again
- [x] Add instructors to review a PR 
  - [x] A feature being refactored
  - [x] Tests being written
